import 'package:kiwi/kiwi.dart';
import 'package:vegetable_orders_project/features/categories/get_category_bloc.dart';
import 'package:vegetable_orders_project/features/confirm_code/confirm_code_bloc.dart';
import 'package:vegetable_orders_project/features/forget_password/forget_password_bloc.dart';
import 'package:vegetable_orders_project/features/get_cities/get_cities_bloc.dart';
import 'package:vegetable_orders_project/features/products/products_bloc.dart';
import 'package:vegetable_orders_project/features/register/register_bloc.dart';
import 'package:vegetable_orders_project/features/search_product/search_products_bloc.dart';
import 'package:vegetable_orders_project/features/slider/slider_bloc.dart';
import '../features/address/get_delete_address/get_delete_address_bloc.dart';
import '../features/address/set_address/set_address_bloc.dart';
import '../features/cart/cart_bloc.dart';
import '../features/category_products/get_category_products_bloc.dart';
import '../features/change_password/change_password_bloc.dart';
import '../features/login/login_bloc.dart';
import '../features/logout/logout_bloc.dart';
import '../features/my_account/contact_us/contact_us_bloc.dart';
import '../features/my_account/edit_password/edit_password_bloc.dart';
import '../features/my_account/edit_profile/edit_profile_bloc.dart';
import '../features/my_account/get_profile/get_profile_bloc.dart';
import '../features/my_account/policy_about_terms/policy_about_terms_bloc.dart';
import '../features/my_account/question/question_bloc.dart';
import '../features/my_account/suggestions/suggestions_bloc.dart';
import '../features/my_account/wallet/wallet_bloc.dart';
import '../features/my_orders/my_orders_bloc.dart';
import '../features/notifications/notifications_bloc.dart';
import '../features/products_rate/products_rate_bloc.dart';
import '../features/search_category/search_category_bloc.dart';
import '../features/similar_products/similar_products_bloc.dart';


void initKiwi() {
  KiwiContainer container = KiwiContainer();
  container.registerFactory((container) => LoginBloc());
  container.registerFactory((container) => RegisterBloc());
  container.registerFactory((container) => GetCitiesBloc());
  container.registerFactory((container) => ForgetPasswordBloc());
  container.registerFactory((container) => ConfirmCodeBloc());
  container.registerFactory((container) => ChangePasswordBloc());
  container.registerFactory((container) => SearchProductsBloc());
  container.registerFactory((container) => GetCategoryProductsBloc());
  container.registerFactory((container) => GetSearchCategoryBloc());
  container.registerFactory((container) => GetSimilarProductBloc());
  container.registerFactory((container) => ProductRateBloc());
  container.registerFactory((container) => NotificationsBloc());
  container.registerFactory((container) => ContactUsBloc());
  container.registerFactory((container) => WalletBloc());
  container.registerFactory((container) => EditPasswordBloc());
  container.registerFactory((container) => QuestionsBloc());
  container.registerFactory((container) => PolicyBloc());
  container.registerFactory((container) => SuggestionsBloc());
  container.registerFactory((container) => LogoutBloc());
  container.registerSingleton((container) => SliderBloc()..add(SliderEvent()));
  container.registerSingleton((container) => GetCategoryBloc()..add(GetCategoryEvent()));
  container.registerSingleton((container) => ProductsBloc()..add(ProductsEvent()));
  container.registerSingleton((container) => CartBloc());
  container.registerSingleton((container) => MyOrdersBloc());
  container.registerSingleton((container) => SetUpdateAddressBloc());
  container.registerSingleton((container) => GetDeleteAddressesBloc());
  container.registerSingleton((container) => ProfileBloc());
  container.registerSingleton((container) => EditProfileBloc());
}